version: '3.8'

services:
  dummyjson-client:
    image: dummyjson-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "default"